import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import * as schema from './schema.js';

export type Db = ReturnType<typeof createDb>;

export function createDb(connectionString: string) {
  const sql = postgres(connectionString);
  return drizzle(sql, { schema });
}

export async function runMigrations(connectionString: string) {
  // Drizzle migrate requires a meta/_journal.json generated by drizzle-kit generate.
  // If it doesn't exist (e.g. schema was applied via db:push), skip gracefully.
  const { existsSync } = await import('fs');
  const journalPath = new URL('../../migrations/meta/_journal.json', import.meta.url);
  if (!existsSync(journalPath)) {
    console.log('[cloud-api] No migration journal found, skipping migrations (schema already applied via db:push)');
    return;
  }
  const sql = postgres(connectionString, { max: 1 });
  const db = drizzle(sql);
  await migrate(db, { migrationsFolder: './migrations' });
  await sql.end();
}

export * from './schema.js';
